apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: dev
  namespace: dev
rules: 
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
 name: prod
 namespace: prod
rules: 
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]  

