apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-dev
  namespace: dev
subjects:
- kind: ServiceAccount
  name: sa-dev
  namespace: dev
roleRef:
  kind: Role
  name: role-dev
  apiGroup: rbac.authorization.k8s.io



---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-prod
  namespace: prod
subjects:
- kind: ServiceAccount
  name: sa-prod
  namespace: prod
roleRef:
  kind: Role
  name: role-prod
  apiGroup: rbac.authorization.k8s.io
